Add Dolphin Bug lookup
AlexApps99/DolphinDiscord pull request #5
Opened 2020-12-13 18:23 UTC by techydude0713

This PR adds functionality to find bug reports in Dolphin Redmine, by using a [hidden JSON API](https://www.redmine.org/projects/redmine/wiki/rest_api).
If a issue number is entered, it will find the information tied to the ID.
<img width="200" alt="Screen Shot 2020-12-13 at 1 13 01 PM" src="https://user-images.githubusercontent.com/39745188/102020124-1d630b00-3d45-11eb-8760-f4d9551fdd51.png">

If a non-number search is used, then it will show the top three results.
<img width="200" alt="Screen Shot 2020-12-13 at 1 16 34 PM" src="https://user-images.githubusercontent.com/39745188/102020189-75017680-3d45-11eb-912a-9e782ffbab6d.png">
In this instance, Redmine searches for the word "Vulkan" in issue titles, descriptions and comments.

2020-12-14 03:57 UTC, AlexApps99 requested changes
This looks awesome! Looking forward to merging this

2020-12-14 03:57 UTC, AlexApps99 commented on categories/Search.py
> +    if (query.isdigit()):
This should use `isdecimal()`, see [here](https://stackoverflow.com/questions/44891070/whats-the-difference-between-str-isdigit-isnumeric-and-isdecimal-in-python)

2020-12-14 20:46 UTC, AlexApps99 commented
OK, I'll try merge it now, fingers crossed it works

2020-12-14 20:46 UTC, merged

2020-12-14 20:53 UTC, AlexApps99 commented
It's working on the server now, thank you for your amazing contribution!

2020-12-15 01:25 UTC, techydude0713 commented
Great! Glad it worked out.